version: 2.1
jobs:
  unit:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
        environment:
          LOG_LEVEL: DEBUG
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake # For installing snappy
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
      - run: bundle exec rubocop

  functional-with-wurstmeister:
    parameters:
      kafka-version:
        type: string
    docker:
      - image: cimg/ruby:2.7
        environment:
          LOG_LEVEL: DEBUG
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:<< parameters.kafka-version >>
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
      - image: wurstmeister/kafka:<< parameters.kafka-version >>
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9093
          KAFKA_PORT: 9093
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
      - image: wurstmeister/kafka:<< parameters.kafka-version >>
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9094
          KAFKA_PORT: 9094
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake # For installing snappy
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec --profile --tag functional spec/functional

  functional-with-bitnami:
    parameters:
      kafka-version:
        type: string
    docker:
      - image: cimg/ruby:2.7
        environment:
          LOG_LEVEL: DEBUG
      - image: bitnami/zookeeper
        environment:
          ALLOW_ANONYMOUS_LOGIN: yes
      - image: bitnami/kafka:<< parameters.kafka-version >>
        environment:
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
      - image: bitnami/kafka:<< parameters.kafka-version >>
        environment:
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
          KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
      - image: bitnami/kafka:<< parameters.kafka-version >>
        environment:
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
          KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake # For installing snappy
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec --profile --tag functional spec/functional

workflows:
  version: 2
  test:
    jobs:
      - unit:
          name: unit-ruby-<< matrix.ruby-version >>
          matrix:
            parameters:
              ruby-version:
                - "2.5"
                - "2.6"
                - "2.7"
                - "3.0"
                - "3.1"
      - functional-with-wurstmeister:
          name: functional-kafka-<< matrix.kafka-version >>
          matrix:
            parameters:
              kafka-version:
                - 2.11-0.11.0.3
                - 2.11-1.0.2
                - 2.11-1.1.1
                - 2.11-2.0.1
                - 2.12-2.1.1
                - 2.12-2.2.1
                - 2.12-2.3.1
                - 2.12-2.4.0
                - 2.12-2.5.0
                - 2.13-2.6.0
      - functional-with-bitnami:
          name: functional-kafka-<< matrix.kafka-version >>
          matrix:
            parameters:
              kafka-version:
                - "2.7.0"
                - "2.8"
                - "3.0"
                - "3.1"
